Feature/name user appbar
marcinmierzejewski/goit-final-project-questify pull request #15
Opened 2022-12-10 14:06 UTC by marcinmierzejewski

Fixed desktop header view
Added logic to the logout button
Added Login on header for not logged user

2022-12-10 17:06 UTC, dawidmarek95x requested changes
Kilka zmian do wprowadzenia

2022-12-10 20:04 UTC, marcinmierzejewski commented on src/components/UserMenu/UserMenu.jsx
> +          <img src={logoutIcon} alt="Log Out" width="21.58"></img>
Dzieki za fajny sposób importowania ikon, nie widziałem tego wcześniej. Teraz kod ładniej wygląda

2022-12-10 20:04 UTC, marcinmierzejewski commented on src/components/AppBar/AppBar.styled.js
>    @media screen and (max-width: 320px) {
Tak, że nie powinno się tak na sztywno dawać wysokości. Poprawione

2022-12-10 20:04 UTC, marcinmierzejewski commented on src/components/AppBar/AppBar.styled.js
> +
Tu miałem domyślne właściwości 50px bez media screen, ale zrobilem wq twojej, to jest bardziej prawilnie

2022-12-10 20:04 UTC, marcinmierzejewski commented on src/components/AppBar/AppBar.styled.js
>    @media screen and (max-width: 320px) {
Poprawione :)

2022-12-10 21:01 UTC, dawidmarek95x requested changes
Jeszcze jedna drobna zmiana, bo jest zbędny kod :)

2022-12-10 21:01 UTC, dawidmarek95x commented on src/components/AppBar/AppBar.styled.js
> +
Jeżeli chcemy być Pixel Perfect to tutaj musi być te 49px z prawej zamiast 50px, żeby zagrało się co do piksela z kartami poniżej, więc możesz, ale nie musisz zmieniać :)

2022-12-10 22:59 UTC, marcinmierzejewski commented on src/components/UserMenu/UserMenu.styled.js
> +
done

2022-12-11 00:02 UTC, dawidmarek95x approved these changes
Wszystko dobrze, zatwierdzam :)

2022-12-11 00:02 UTC, merged